version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      - "/.github/actions/android"
      - "/.github/actions/common"
      - "/.github/actions/debian"
      - "/.github/actions/ios"
      - "/.github/actions/macos"
      - "/.github/actions/screenshot-android"
      - "/.github/actions/screenshot-ipad"
      - "/.github/actions/screenshot-iphone"
      - "/.github/actions/windows"
    schedule:
      interval: "daily"