name: "Debian Workflow"

inputs:
  VERSION_NAME:
    description: 'Version Name to be used for build'
    required: false
    default: '1.0.0'
  VERSION_CODE:
    description: 'Version Code to be used for build'
    required: true
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
        flutter-version-file: pubspec.yaml

    - name: Install Linux dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          liblzma-dev \
          clang \
          cmake \
          ninja-build \
          pkg-config \
          libglib2.0-dev \
          libblkid-dev \
          libgcrypt20-dev \
          libusb-1.0-0-dev \
          libudev-dev

    - name: Get Flutter packages
      shell: bash
      run: flutter pub get

    - name: Patch hid_tool Linux plugin
      shell: bash
      run: |
        sed -i '/g_autoptr(FlMethodCall) method_call/,/fl_method_channel_get_codec(self->channel));/d' \
          linux/flutter/ephemeral/.plugin_symlinks/hid_tool/linux/hid_tool_plugin.cc

    - name: Build Linux (Debian) App
      shell: bash
      env:
        VERSION_NAME: ${{ inputs.VERSION_NAME }}
        VERSION_CODE: ${{ inputs.VERSION_CODE }}
      run: |
        flutter build linux --build-name $VERSION_NAME --build-number $VERSION_CODE
